<?php echo UIElements::disclaimer($mt); ?>

<a name="v5"></a>
    <h1 id="v5.4.3">PHP 5.4.3 (<?php echo $t["currentStable"] ?>)</h1>

<h2><?php echo $t["sourceCode"] ?></h2>
<ul>
 <li>
  <a href="http://php.net/get/php-5.4.3.tar.bz2/from/a/mirror">PHP 5.4.3 (tar.bz2)</a> [10,886Kb] -  08 May 2012<br />
  <span class="md5sum">md5: 51f9488bf8682399b802c48656315cac</span>
 </li>
 <li>
  <a href="http://php.net/get/php-5.4.3.tar.gz/from/a/mirror">PHP 5.4.3 (tar.gz)</a> [13,720Kb] -  08 May 2012<br />
  <span class="md5sum">md5: c9dccc89cc89d39e84f6e6f0cf1c8a65</span>
 </li>
</ul>

<hr />
    <h1 id="v5.3.13">PHP 5.3.13 (<?php echo $t["oldStable"] ?>)</h1>

<h2><?php echo $t["sourceCode"] ?></h2>
<ul>
 <li>
  <a href="http://php.net/get/php-5.3.13.tar.bz2/from/a/mirror">PHP 5.3.13 (tar.bz2)</a> [11,129Kb] -  08 May 2012<br />
  <span class="md5sum">md5: 370be99c5cdc2e756c82c44d774933c8</span>
 </li>
 <li>
  <a href="http://php.net/get/php-5.3.13.tar.gz/from/a/mirror">PHP 5.3.13 (tar.gz)</a> [14,564Kb] -  08 May 2012<br />
  <span class="md5sum">md5: 179c67ce347680f468edbfc3c425476a</span>
 </li>
</ul>

<hr />
<h2><?php echo $t["winBinaries"] ?></h2>
<p>
<?php echo $t["winBinariesEx"] ?> <a href='http://windows.php.net/download/'>http://windows.php.net/download/</a>.
</p>
<hr />

<h1><?php echo $t["gnuPg"] ?></h1>
<p>
<?php echo $t->_("gnuPgEx", array('git' => "<a href='http://php.net/git.php'>PHP Git Repository</a>")) ?>
</p>
<h2>PHP 5.4</h2>
<pre>
pub   2048D/5DA04B5D 2012-03-19
      Key fingerprint = F382 5282 6ACD 957E F380  D39F 2F79 56BC 5DA0 4B5D
uid                  Stanislav Malyshev (PHP key) &lt;smalyshev@gmail.com&gt;
uid                  Stanislav Malyshev (PHP key) &lt;stas@php.net&gt;
uid                  Stanislav Malyshev (PHP key) &lt;smalyshev@sugarcrm.com&gt;
</pre>
<pre>
pub   4096R/7267B52D 2012-03-20 [expires: 2016-03-19]
      Key fingerprint = 0B96 609E 270F 565C 1329  2B24 C13C 70B8 7267 B52D
uid                  David Soria Parra &lt;dsp@php.net&gt;
</pre>
<h2>PHP 5.3</h2>
<pre>
pub   2048R/FC9C83D7 2012-03-18 [expires: 2017-03-17]
      Key fingerprint = 0A95 E9A0 2654 2D53 835E  3F3A 7DEC 4E69 FC9C 83D7
uid                  Johannes Schlüter &lt;johannes@schlueters.de&gt;
uid                  Johannes Schlüter &lt;johannes@php.net&gt;
</pre>

 </div>