
<?php echo UIElements::disclaimer($mt); ?>

<h1>Documentation</h1>

<p>
 The PHP Manual is available online in a selection of languages.
 Please pick a language from the list below.
</p>

<p>
 You can learn how to integrate our online manual with various tools, including
 your web browser, on our <a href="tips.php">quick reference tips</a> page.
 You can also get more information about php.net URL shortcuts by visiting our
 <a href="urlhowto.php">URL howto page</a>.
</p>

<p>
 Note, that many languages are just under translation, and
 the untranslated parts are still in English. Also some translated
 parts might be outdated. The translation teams are open to
 contributions. 
</p>

<table class="table table-bordered table-striped responsive-utilities">
 <tr>
  <th>Formats</th>
  <th>Destinations</th>
 </tr>
 <tr>
  <th class="sub">View Online</th>
  <td>
  <strong><a href="http://www.php.net/manual/en/">English</a></strong>,
  <a href="http://www.php.net/manual/pt_BR/">Brazilian Portuguese</a>,
  <a href="http://www.php.net/manual/zh/">Chinese (Simplified)</a>,
  <a href="http://www.php.net/manual/fr/">French</a>,
  <a href="http://www.php.net/manual/de/">German</a>,
  <a href="http://www.php.net/manual/ja/">Japanese</a>,
  <a href="http://www.php.net/manual/pl/">Polish</a>,
  <a href="http://www.php.net/manual/ro/">Romanian</a>,
  <a href="http://www.php.net/manual/ru/">Russian</a>,
  <a href="http://www.php.net/manual/fa/">Persian</a>,
  <a href="http://www.php.net/manual/es/">Spanish</a>,
  <a href="http://www.php.net/manual/tr/">Turkish</a>
  </td>
 </tr>
 <tr>
  <th class="sub">Downloads</th>
  <td>
   For downloadable formats, please visit our
   <a href="http://www.php.net/download-docs.php">documentation downloads</a> page.
  </td>
 </tr>
</table>

<h2>More documentation</h2>
<ul>
 <li>
  If you are interested in how the documentation is edited and translated,
  you should read the <a href="http://doc.php.net/php/dochowto/">Documentation HOWTO</a>.
 </li>
 <li>
  <a href="http://gtk.php.net/docs.php">PHP-GTK related documentation</a>
  is hosted on the PHP-GTK website.
 </li>
 <li>
  <a href="http://pear.php.net/manual/">Documentation of PEAR and the various
  packages</a> can be found on a separate server.
 </li>
 <li>
  You can still read a copy of the original <a href="http://www.php.net/manual/phpfi2.php">PHP/FI
  2.0 Manual</a> on our site, which we only host for historical purposes.
  The same applies to the <a href="http://www.php.net/manual/php3.php">PHP 3 Manual</a>.
 </li>
</ul>