

<p><h1>About Demo</h1></p>

<p>
This is a sample application for the <a href="http://phalconphp.com">Phalcon PHP Framework</a>. 
We expect to implement as many features as possible to show how the framework works and its potential.
Please write us if you have any feedback or comments. Feel free to clone the code of this application <a href="https://github.com/phalcon/php-site">here</a>. The purpose of this application is merely academic.
This is <b>not</b> an official mirror for PHP. Don't trust any information or download any PHP version from this site.
<a href="https://www.php.net">Access the official site</a>.
.Thanks!.
</p>

<p>All the content, logos, graphical elements are Copyright © 2001-2012 The PHP Group. All rights reserved.</p>