
<h1>Mailing Lists</h1>

<p>
 There are many PHP-related mailing lists available on our server.
 Most of them are archived, and all of them are available as newsgroups
 on our <a href="news://news.php.net">news server</a>. You can search
 some mailing lists right from this website from <a href="http://php.net/search.php">the
 search page</a> or by using the search input box selecting the
 appropriate option on the top-right of every page.
</p>
<p>
 There is an experimental web interface for the news server at
 <a href="http://news.php.net/">http://news.php.net/</a>, and
 there are also other archives provided by
 <a href="http://marc.info/">Marc</a>.
</p>

<h2>Posting guidelines</h2>

<p>
 When posting to mailing lists or newsgroups, please keep the following in mind:
</p>

<ul>
 <li>
  Use a valid email address. Every new poster's email address
  is checked for validity through confirmation.
 </li>
 <li>
  Send plain ASCII messages, no HTML-formatted emails please.
 </li>
 <li>
  Turn on word wrapping so your entire message doesn't show up on
  a single line.
 </li>
 <li>
  Be sure to click <strong>Reply-All</strong> to reply to list. Clicking
  <strong>Reply</strong> will email the author of the message privately.
 </li>
 <li>
  No attachments please, just post a URL if you want someone to
  look at something.
 </li>
 <li>
  Don't GPG/PGP sign your messages. If you want people to be able
  to send you encrypted email, stick your key-locator in your signature
 </li>
 <li>
  Don't hijack other peoples' threads. To post on a new topic, start
  a new message, don't reply and just change the subject.
 </li>
 <li>
  Check the archives before posting a question, chances are it has
  already been asked and answered a few times.
 </li>
 <li>
  When asking a question, don't just tell us, &quot;it doesn't work&quot;.
  Tell us what you are trying to accomplish, a <strong>short</strong> code
  snippet showing how you tried to solve it, what you expected to get and
  what you got instead.
 </li>
</ul>
<p>
 And make sure you have read our
 <a href="http://php.net/reST/php-src/trunk_README.MAILINGLIST_RULES">Mailinglist Rules</a>.
</p>

<form method="post" action="http://php.net/mailing-lists.php">

<h2 id="general">General Mailing Lists</h2>

<table class="table table-bordered table-striped responsive-utilities">
<tr><th>General mailing lists for PHP users</th><th>Moderated</th><th>Archive</th><th>Newsgroup</th><th>Normal</th><th>Digest</th></tr>
<tr align="center"><td align="left"><strong>Announcements</strong><br /><small>Announcements of new PHP releases are sent to this very low-volume list</small></td><td>yes</td><td>n/a</td><td><a href="news://news.php.net/php.announce">yes</a> <a href="http://news.php.net/group.php?group=php.announce">http</a></td><td><input name="maillist" type="radio" value="php-announce" /></td><td>n/a</td></tr>
<tr align="center"><td align="left"><strong>General user list</strong><br /><small>This is a high volume list for general PHP support; ask PHP questions here</small></td><td>no</td><td><a href="http://marc.info/?l=php-general">yes</a></td><td><a href="news://news.php.net/php.general">yes</a> <a href="http://news.php.net/group.php?group=php.general">http</a></td><td><input name="maillist" type="radio" value="php-general" /></td><td><input name="maillist" type="radio" value="php-general-digest" /></td></tr>
<tr align="center"><td align="left"><strong>Windows PHP users list</strong><br /><small>Using PHP on Microsoft Windows</small></td><td>no</td><td><a href="http://marc.info/?l=php-windows">yes</a></td><td><a href="news://news.php.net/php.windows">yes</a> <a href="http://news.php.net/group.php?group=php.windows">http</a></td><td><input name="maillist" type="radio" value="php-windows" /></td><td><input name="maillist" type="radio" value="php-windows-digest" /></td></tr>
<tr><th>Subject specific lists for PHP users</th><th>Moderated</th><th>Archive</th><th>Newsgroup</th><th>Normal</th><th>Digest</th></tr>
<tr align="center"><td align="left"><strong>Installation issues and problems</strong><br /><small>How to install PHP with particular configurations and servers</small></td><td>no</td><td><a href="http://marc.info/?l=php-install">yes</a></td><td><a href="news://news.php.net/php.install">yes</a> <a href="http://news.php.net/group.php?group=php.install">http</a></td><td><input name="maillist" type="radio" value="php-install" /></td><td><input name="maillist" type="radio" value="php-install-digest" /></td></tr>
<tr align="center"><td align="left"><strong>Databases and PHP</strong><br /><small>This list is for the discussion of PHP database topics</small></td><td>no</td><td><a href="http://marc.info/?l=php-db">yes</a></td><td><a href="news://news.php.net/php.db">yes</a> <a href="http://news.php.net/group.php?group=php.db">http</a></td><td><input name="maillist" type="radio" value="php-db" /></td><td><input name="maillist" type="radio" value="php-db-digest" /></td></tr>
<tr align="center"><td align="left"><strong>Unicode and Internationalization</strong><br /><small>Unicode support, Internationalization (i18n) and localization (l10n) issues and features</small></td><td>no</td><td><a href="http://marc.info/?l=php-i18n">yes</a></td><td><a href="news://news.php.net/php.i18n">yes</a> <a href="http://news.php.net/group.php?group=php.i18n">http</a></td><td><input name="maillist" type="radio" value="php-i18n" /></td><td><input name="maillist" type="radio" value="php-i18n-digest" /></td></tr>
<tr align="center"><td align="left"><strong>PHP evangelism mailing list</strong><br /><small>A list for people interested in promoting PHP and learning good reasons to support PHP in the enterprise</small></td><td>yes</td><td><a href="http://marc.info/?l=php-evangelism">yes</a></td><td><a href="news://news.php.net/php.evangelism">yes</a> <a href="http://news.php.net/group.php?group=php.evangelism">http</a></td><td><input name="maillist" type="radio" value="php-evangelism" /></td><td><input name="maillist" type="radio" value="php-evangelism-digest" /></td></tr>
<tr align="center"><td align="left"><strong>PHP SOAP list</strong><br /><small>List for the SOAP developers</small></td><td>no</td><td>n/a</td><td><a href="news://news.php.net/php.soap">yes</a> <a href="http://news.php.net/group.php?group=php.soap">http</a></td><td><input name="maillist" type="radio" value="soap" /></td><td>n/a</td></tr>
<tr><th>Non-English language mailing lists</th><th>Moderated</th><th>Archive</th><th>Newsgroup</th><th>Normal</th><th>Digest</th></tr>
<tr align="center"><td align="left"><strong>Spanish PHP Mailing list</strong><br /><small>List for Spanish speaking people interested in PHP</small></td><td>no</td><td>n/a</td><td><a href="news://news.php.net/php.general.es">yes</a> <a href="http://news.php.net/group.php?group=php.general.es">http</a></td><td><input name="maillist" type="radio" value="php-es" /></td><td>n/a</td></tr>
</table>

<h2 id="internals">Internals Mailing Lists</h2>

<table class="table table-bordered table-striped responsive-utilities">
<tr><th>PHP and Zend Engine internals lists</th><th>Moderated</th><th>Archive</th><th>Newsgroup</th><th>Normal</th><th>Digest</th></tr>
<tr align="center"><td align="left"><strong>Internals list</strong><br /><small>A medium volume list for those who want to help out with the development of PHP</small></td><td>no</td><td><a href="http://marc.info/?l=php-internals">yes</a></td><td><a href="news://news.php.net/php.internals">yes</a> <a href="http://news.php.net/group.php?group=php.internals">http</a></td><td><input name="maillist" type="radio" value="internals" /></td><td><input name="maillist" type="radio" value="internals-digest" /></td></tr>
<tr align="center"><td align="left"><strong>Windows Internals list</strong><br /><small>A low volume list for those who want to help out with the development of PHP on Windows</small></td><td>no</td><td>n/a</td><td><a href="news://news.php.net/php.internals.win">yes</a> <a href="http://news.php.net/group.php?group=php.internals.win">http</a></td><td><input name="maillist" type="radio" value="internals-win" /></td><td><input name="maillist" type="radio" value="internals-win-digest" /></td></tr>
<tr align="center"><td align="left"><strong>Git commit list</strong><br /><small>All commits to internals (php-src) and the Zend Engine are posted to this list automatically</small></td><td>yes</td><td><a href="http://marc.info/?l=php-cvs">yes</a></td><td><a href="news://news.php.net/php.cvs">yes</a> <a href="http://news.php.net/group.php?group=php.cvs">http</a></td><td><input name="maillist" type="radio" value="php-cvs" /></td><td>n/a</td></tr>
<tr align="center"><td align="left"><strong>Daily Git commit summary</strong><br /><small>Daily changelog and NEWS file updates</small></td><td>yes</td><td>n/a</td><td>n/a</td><td><input name="maillist" type="radio" value="php-cvs-daily" /></td><td>n/a</td></tr>
<tr align="center"><td align="left"><strong>Git pull requests</strong><br /><small>Pull requests from Github</small></td><td>no</td><td>n/a</td><td><a href="news://news.php.net/php.git-pulls">yes</a> <a href="http://news.php.net/group.php?group=php.git-pulls">http</a></td><td><input name="maillist" type="radio" value="git-pulls" /></td><td>n/a</td></tr>
<tr align="center"><td align="left"><strong>Quality Assurance list</strong><br /><small>List for the members of the PHP-QA Team</small></td><td>no</td><td><a href="http://marc.info/?l=php-qa">yes</a></td><td><a href="news://news.php.net/php.qa">yes</a> <a href="http://news.php.net/group.php?group=php.qa">http</a></td><td><input name="maillist" type="radio" value="php-qa" /></td><td>n/a</td></tr>
<tr align="center"><td align="left"><strong>PDO Developmental list</strong><br /><small>Discuss the past, present and future of PDO</small></td><td>no</td><td>n/a</td><td><a href="news://news.php.net/php.pdo">yes</a> <a href="http://news.php.net/group.php?group=php.pdo">http</a></td><td><input name="maillist" type="radio" value="pdo" /></td><td><input name="maillist" type="radio" value="pdo-digest" /></td></tr>
<tr><th>PHP internal website mailing lists</th><th>Moderated</th><th>Archive</th><th>Newsgroup</th><th>Normal</th><th>Digest</th></tr>
<tr align="center"><td align="left"><strong>PHP php.net internal infrastructure discussion</strong><br /><small>List for discussing and maintaining the php.net web infrastructure.<br />
       For general PHP support questions, see "General Mailing Lists" or the <a href="http://php.net/support.php">support page</a></small></td><td>no</td><td>n/a</td><td><a href="news://news.php.net/php.webmaster">yes</a> <a href="http://news.php.net/group.php?group=php.webmaster">http</a></td><td><input name="maillist" type="radio" value="php-webmaster" /></td><td>n/a</td></tr>
<tr><th>PHP documentation mailing lists</th><th>Moderated</th><th>Archive</th><th>Newsgroup</th><th>Normal</th><th>Digest</th></tr>
<tr align="center"><td align="left"><strong>Documentation discussion</strong><br /><small>List for discussing the PHP documentation</small></td><td>no</td><td><a href="http://marc.info/?l=phpdoc">yes</a></td><td><a href="news://news.php.net/php.doc">yes</a> <a href="http://news.php.net/group.php?group=php.doc">http</a></td><td><input name="maillist" type="radio" value="phpdoc" /></td><td>n/a</td></tr>
<tr align="center"><td align="left"><strong>Documentation changes and commits</strong><br /><small>Changes to the documentation are posted here</small></td><td>yes</td><td><a href="http://marc.info/?l=php-doc-cvs">yes</a></td><td><a href="news://news.php.net/php.doc.cvs">yes</a> <a href="http://news.php.net/group.php?group=php.doc.cvs">http</a></td><td><input name="maillist" type="radio" value="doc-cvs" /></td><td>n/a</td></tr>
<tr align="center"><td align="left"><strong>Documentation bugs</strong><br /><small>Documentation bug activity (translations, sources, and build system) are posted here</small></td><td>yes</td><td><a href="http://marc.info/?l=php-doc-bugs">yes</a></td><td><a href="news://news.php.net/php.doc.bugs">yes</a> <a href="http://news.php.net/group.php?group=php.doc.bugs">http</a></td><td><input name="maillist" type="radio" value="doc-bugs" /></td><td>n/a</td></tr>
</table>

<p class="center">
 <strong>Email:</strong>
 <input type="text" name="email" size="40" value="user@example.com" />
 <input type="submit" name="action" value="Subscribe" />
 <input type="submit" name="action" value="Unsubscribe" />
</p>

</form>

<p>
 You will be sent a confirmation mail at the address you wish to
 be subscribed or unsubscribed, and only added to the list after
 following the directions in that mail.
</p>

<p>
 <strong>Warning:</strong> The PHP users mailing list gets close to 1500-2000
 messages per month currently. Do the math. That translates to about 60
 messages per day. If your mailbox can't handle this sort of traffic you
 might want to consider subscribing to the digest list instead (two messages
 per day), using the news server, or reading the mailing list using the
 archives. 
</p>

<h2>Mailing list options</h2>

<p>
 All of the mailing lists hosted at <a
 href="http://lists.php.net/">lists.php.net</a> are managed using the <a
 href="http://www.ezmlm.org/">ezmlm-idx</a> mailing list software.
 There are a variety of commands you can use to modify your subscription.
 Either send a message to <code>php-whatever-help@lists.php.net</code> (as in,
 <code>php-general-help@lists.php.net</code>) or you can view the commands for
 ezmlm <a href="http://www.ezmlm.org/ezman/ezman1.html">here.</a>
</p>

