
<div class="row">
	<div class="span4 short-panel">

		<h3><?php echo $t["otherBinaries"]; ?></h3>
		<p><?php echo $t["otherBinariesEx"]; ?></p>
		<ul class="toc">
		 <li><a href="http://publib-b.boulder.ibm.com/Redbooks.nsf/RedpieceAbstracts/redp3639.html">AS/400</a></li>
		 <li><a href="http://www.ampps.com/">Mac OS X (AMPPS)</a></li>
		 <li><a href="http://www.mamp.info/">Mac OS X (MAMP)</a></li>
		 <li><a href="http://developer.novell.com/wiki/index.php/PHP_for_NetWare">Novell NetWare</a></li>
		 <li><a href="http://os2ports.smedley.info/index.php?page=php-5">OS/2</a></li>
		 <li><a href="http://www.cp15.org/php/">RISC OS</a></li>
		 <li><a href="http://freeware.sgi.com/index-by-alpha.html#php">SGI IRIX 6.5.x</a></li>
		 <li>Solaris (<a href="http://sunfreeware.com/programlistsparc10.html#php">SPARC</a>, <a href="http://sunfreeware.com/programlistintel10.html#php">INTEL</a>)</li>
		 <li><a href="http://www.opencsw.org/packages/php5">Solaris OpenCSW packages</a></li>
		 <li><a href="http://iuscommunity.org/">Redhat/CentOS Binaries</a></li>
		</ul>

		<h3><?php echo $t["devVersions"]; ?></h3>
		<p>
			<?php echo $t->_("notProduction", array("snaps" => '<a href="http://snaps.php.net/">snaps.php.net</a>')); ?>	 
		</p>
		<p>
			<?php echo $t->_("git", array("git" => '<a href="http://php.net/git.php">Git</a>')); ?>		 
		</p>
		<div class="information">
			<p>
				<?php echo $t->_("olderReleases", array("releases" => '<a href="http://php.net/releases/">releases</a>')); ?>		 
			</p>
		</div>
		<br />

		<h3><?php echo $t["otherDownloads"]; ?></h3>
		<p>
		 <a href="http://pear.php.net/packages.php">PEAR
		 packages</a>, <a href="http://pecl.php.net/packages.php">PECL hosted
		 PHP extensions</a> and <a href="http://gtk.php.net/download.php">PHP-GTK
		 source and binaries</a> are available on their own pages.
		</p>

		<p>
		 For downloadable PHP manual packages, go to the
		 <a href="http://php.net/download-docs.php">documentation download</a>
		 page.
		</p>

		<p>
		 Get some
		 <a href="http://php.net/download-logos.php">PHP logos</a>
		 for your site, and some PHP icons to use on
		 your computer.
		</p>

	</div>
    <div class="span8 large-panel"><?php echo $this->getContent() ?></div>    
</div>	