
<div class="row">
    <div class="span8 large-panel"><?php echo $this->getContent() ?></div>
    <div class="span4 short-panel">

		<h3><?php echo $t["whatIs"] ?></h3>
		<p>
			<?php echo $t->_("phpIs", array(
				"manual" => '<a href="http://www.php.net/docs.php">'.$t["manual"].'</a>',
				"tutorial" => '<a href="http://www.php.net/tut.php">'.$t["tutorial"].'</a>',
				'links section' => '<a href="http://www.php.net/links.php">'.$t["linkSection"].'</a>'
			)) ?>
		</p>

		<p>
			<?php echo $t->_("popular", array(
				"survey" => '<a href="http://www.php.net/usage.php">'.$t["survey"].'</a>',				
			)) ?>	
		</p>

		<div class="release">
			<strong><?php echo $t["stable"] ?></strong>

			<ul>
				<li><?php echo Phalcon_Tag::linkTo("downloads/#v5", $t->_("stable-ver", array(
					"branch" => "5.4", 
					"version" => "5.4.3"
				))) ?></li>
				<li><?php echo Phalcon_Tag::linkTo("downloads/#v5", $t->_("stable-ver", array(
					"branch" => "5.3",
					"version" => "5.3.13"
				))) ?></li>
			</ul>
		</div>

		<p>
			<strong><?php echo $t["candidates"] ?></strong>

			<ul>
				<li><a href="http://qa.php.net/">5.4.4RC2 (30 May 2012)</a></li>
    			<li><a href="http://qa.php.net/">5.3.14RC1 (17 May 2012)</a></li>
			</ul>
		</p>

		<h3><a href="http://www.php.net/thanks.php"><?php echo $t["thanks"] ?></a></h3>
		<ul class="simple">
			<li><a href="http://www.easydns.com/?V=698570efeb62a6e2" title="DNS Hosting provided by easyDNS">easyDNS</a></li>
			<li><a href="http://www.directi.com/">Directi</a></li>
			<li><a href="http://promote.pair.com/direct.pl?php.net">pair Networks</a></li>
			<li><a href="http://www.servercentral.net/">Server Central</a></li>
			<li><a href="http://www.hostedsolutions.com/">Hosted Solutions</a></li>
			<li><a href="http://www.spry.com/">Spry VPS Hosting</a></li>
			<li><a href="http://www.osuosl.org">OSU Open Source Lab</a></li>
			<li><a href="http://www.yahoo.com/">Yahoo! Inc.</a></li>
			<li><a href="http://www.nexcess.net/">NEXCESS.NET</a></li>
			<li><a href="http://www.rackspace.com/">Rackspace</a></li>
			<li><a href="http://www.eukhost.com/">EUKhost</a></li>
			<li><a href="http://www.sohosted.nl/webhosting/">SoHosted Webhosting</a></li>
			<li><a href="http://www.redpill-linpro.com">Redpill Linpro</a></li>
			<li><a href="http://www.facebook.com">Facebook</a></li>
			<li><a href="http://krystal.co.uk">Krystal.co.uk</a></li>
			<li><a href="http://servergrove.com/">ServerGrove</a></li>
			<li><a href="http://www.bauer-kirch.de/">Bauer + Kirch GmbH</a></li>
		</ul>

		<h3><?php echo $t["related"] ?></h3>
		<ul class="simple">
 			<li><a href="http://www.apache.org/">Apache</a></li>
 			<li><a href="http://www.mysql.com/">MySQL</a></li>
 			<li><a href="http://www.postgresql.org/">PostgreSQL</a></li>
 			<li><a href="http://www.zend.com/">Zend Technologies</a></li>
		</ul>

		<h3><?php echo $t["community"] ?></h3>
		<ul class="simple">
 			<li><a href="http://www.linuxfund.org/">LinuxFund.org</a></li>
 			<li><a href="http://ostg.com/">OSTG</a></li>
		</ul>

</div>

