

<div class="row">
	<div class="span4 short-panel">
		<h3>Support tips and links</h3>
		<p>
			We suggest you visit <a href="http://www.php.net/support.php">our support page</a>
			for information about mailing lists on PHP.net and some international
			ones, as well as other support options.
		</p>

		<h3>PHP licensed software</h3>
		<p>
 			Additionally to these links, we have a
 			<a href="http://www.php.net/software">list of software</a> available under
 			the PHP license.
		</p>
    </div>
    <div class="span8 large-panel"><?php echo $this->getContent() ?></div>    
</div>