
<div class="row">
	<div class="span4 short-panel">

		<h3>Would like to unsubscribe yourself?</h3>

		<p>
		 If you have trouble getting off from any of our mailing lists, or
		 would like to unsubscribe from a mailing list not listed here, we
		 have more information for you on <a href="http://php.net/unsub.php">the
		 unsubscription page</a>.
		</p>

		<h3>Other PHP related mailing lists</h3>

		<p>
		 Find the <a href="http://pear.php.net/support/lists.php">PEAR
		 lists</a>, the <a href="http://pecl.php.net/support.php">PECL
		 lists</a>, and the <a href="http://gtk.php.net/resources.php">PHP-GTK
		 lists</a> on their own pages.
		</p> 

		<a name="local"></a>
		<h3>Local Mailing Lists and Newsgroups</h3>

		<ul class="toc">
		 <li><a href="http://groups.google.com/group/dk.edb.internet.webdesign.serverside.php/topics">Danish Newsgroup</a></li>
		 <li><a href="http://groups.google.com/group/fr.comp.lang.php/topics">French Newsgroup</a></li>
		 <li><a href="http://lists.phpbar.de/mailman/listinfo">German Mailing List</a></li>
		 <li><a href="http://groups.google.com/group/de.comp.lang.php.misc/topics">German Newsgroup</a> (also other topics under de.comp.lang.php)</li>
		 <li><a href="http://groups.yahoo.com/group/php_greek/">Greek Mailing List</a></li>
		 <li><a href="http://weblabor.hu/levlistak">Hungarian Mailing List</a></li>
		 <li><a href="http://www.domeus.it/circles/php">Italian Mailing List (at PHPItalia)</a></li>
		 <li><a href="http://ml.php.gr.jp/">The Japanese PHP User Group's Mailing lists</a></li>
		 <li><a href="http://br.groups.yahoo.com/group/php-pt/">Portuguese Mailing List</a></li>
		</ul>

	</div>
    <div class="span8 large-panel"><?php echo $this->getContent() ?></div>    
</div>	