<?php use Phalcon_Tag as Tag; ?>

<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <?php echo Tag::image(array('img/logo.png', 'width' => 80)) ?>
            <form action="http://www.php.net/search.php" method="post" class="navbar-search pull-right">
                <input type="text" name="pattern" class="search-query" placeholder="Search for">
            </form>
        </div>
    </div>
    <div class="navbar-inner navbar-menu">
        <nav>
            <?php echo UIElements::getMenu($this, $mt) ?>        
        </nav>
    </div>
</div>

<div class="container">
    <?php echo $this->getContent() ?>
    <hr>    
</div>

<footer>
    <?php echo Tag::linkTo("copyright", "Copyright © 2001-2012 The PHP Group") ?>
    <div class="language">
           Change language: <?php echo Tag::linkTo("set-language/en", "English") ?>  | <?php echo Tag::linkTo("set-language/es", "Español") ?>
    </div>
</footer>
